### ISSUE TITLE
登录openctp 7*24，合约数为0

### ISSUE THREAD

**Issue by xiehao5** [openctp/ViTrader#11]
仓库中默认的库，可以正常登录simnow，显示合约+交易都没有问题。

然而，使用TTS 6.3.15对应的库替换build目录中默认的库。
编辑TextTrader.ini内容为对应的openctp 7*24登录内容。

在windows和Linux环境中，均显示：

`行情通道登录成功`

但没有合约信息显示。
调试后发现，vDepthMarketDatas.size() = 0

可能是我使用方法不对，敬请大佬不吝赐教。

**Comment by krenx1983** [comment]
github上的dll等二进制文件单独下载可能是坏的，整体clone下来就没问题，openctp官网www.openctp.cn上可以单独下载某个dll
